import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import usePermissions from "../../hooks/usePermissions";
import { buildDocumentPdf, DEFAULT_SECTION_ORDER, SECTION_LABELS } from "../../print/pdf/documentPdfBuilder";
import "./FileSetupPages.css";
import "./PrintTemplateList.css";

const SPACING_PRESETS = [
  { value: "compact", label: "Compact" },
  { value: "normal", label: "Normal" },
  { value: "relaxed", label: "Relaxed" },
];
const ALIGNMENT_PRESETS = [
  { value: "left", label: "Left" },
  { value: "center", label: "Center" },
];

const API_BASE = import.meta.env.VITE_API_URL || "";
const MODULE_KEY = "PRINT.DOCUMENT_TEMPLATES";

// Phase 3A scope only - every field here maps 1:1 to a Phase 2 config field
// that documentPdfBuilder.js actually reads today (see printTemplateService.js's
// CONFIG_SCHEMA). Section reordering, style presets, and column configuration
// are validated by the backend already but not rendered yet - deliberately
// left out of this checkpoint (Phase 3C/3D), not omitted by oversight.
const MODULE_META = {
  invoice: {
    title: "Invoice Templates",
    singularNoun: "Invoice",
    subtitle: "Configure how Invoice documents are printed. Accounting values are never editable here - only presentation.",
    variants: [
      { value: "sales_invoice", label: "Sales Invoice" },
      { value: "service_invoice", label: "Service Invoice" },
      { value: "commercial_invoice", label: "Commercial Invoice" },
      { value: "cash_invoice", label: "Cash Invoice" },
    ],
    defaultPartyLabel: "Bill To",
    listEndpoint: "/api/invoices",
  },
  or: {
    title: "OR Templates",
    singularNoun: "Official Receipt",
    subtitle: "Configure how Official Receipt documents are printed. Accounting values are never editable here - only presentation.",
    variants: [
      { value: "official_receipt", label: "Official Receipt" },
      { value: "collection_receipt", label: "Collection Receipt" },
      { value: "acknowledgement_receipt", label: "Acknowledgement Receipt" },
    ],
    defaultPartyLabel: "Received From",
    listEndpoint: "/api/or",
  },
};

// Matches printTemplateService.js's assertTemplateCode exactly, so the
// client rejects an invalid code before ever reaching the server - the
// backend remains the authoritative check either way.
const TEMPLATE_CODE_PATTERN = /^[a-z0-9][a-z0-9_-]{1,58}[a-z0-9]$/;

function authHeaders() {
  const token = localStorage.getItem("token");
  return token ? { Authorization: `Bearer ${token}` } : {};
}

// Cosmetic only ("Generated by X on ..." footer line, same as
// TransactionPrintOptionsModal.jsx) - reads the already-trusted JWT the
// browser already holds rather than requiring a currentUser prop this
// standalone route (opened from the sidebar, not from within a
// transaction) has no natural source for. Never used for authorization -
// every real permission check happens server-side regardless.
function currentUsername() {
  try {
    const token = localStorage.getItem("token");
    if (!token) return "User";
    const payload = JSON.parse(atob(token.split(".")[1].replace(/-/g, "+").replace(/_/g, "/")));
    return payload.username || "User";
  } catch {
    return "User";
  }
}

function emptyMainForm(moduleType) {
  return {
    templateName: "",
    templateCode: "",
    documentVariant: MODULE_META[moduleType].variants[0].value,
  };
}

function emptyConfigForm(moduleType) {
  return {
    documentTitle: "",
    subtitle: "",
    showCompanyName: true,
    showCompanyAddress: true,
    showTin: true,
    showCopyBadge: true,
    partySectionLabel: MODULE_META[moduleType].defaultPartyLabel,
    showPartyName: true,
    showPartyAddress: true,
    showPartyTin: true,
    showTransactionNumber: true,
    showDate: true,
    showCurrency: true,
    showExchangeRate: true,
    showReferenceNumber: true,
    showPaymentMethod: true,
    showPaymentAccount: true,
    showEwt: true,
    showTotal: true,
    showAmountInWords: true,
    showSystemGeneratedNotice: true,
    showComplianceFooter: true,
    showPageFooter: true,
    // Phase 3C. Left empty here rather than pre-filled with a hardcoded
    // duplicate of the module's default order - loadPreviewData() seeds
    // this from the real built-in config (the single source of truth)
    // the moment it loads, for "add" mode; edit mode reads it straight
    // from the template's own stored config in configToForm() below.
    sectionOrder: [],
    spacingPreset: "normal",
    alignmentPreset: "left",
  };
}

// Reverse of buildConfigPayload() below - loads an existing template's
// stored (already-merged-with-built-in-defaults) config back into the flat
// form shape the modal edits. Every field falls back to `true`/the module
// default only as a defensive fallback for a field the stored config
// somehow omitted - the backend always returns a fully-populated config,
// so in practice these fallbacks are never exercised against real data.
function configToForm(config, moduleType) {
  const d = emptyConfigForm(moduleType);
  if (!config) return d;
  return {
    documentTitle: config.header?.documentTitle || "",
    subtitle: config.header?.subtitle || "",
    showCompanyName: config.header?.showCompanyName ?? d.showCompanyName,
    showCompanyAddress: config.header?.showCompanyAddress ?? d.showCompanyAddress,
    showTin: config.header?.showTin ?? d.showTin,
    showCopyBadge: config.header?.showCopyBadge ?? d.showCopyBadge,
    partySectionLabel: config.party?.sectionLabel || d.partySectionLabel,
    showPartyName: config.party?.showName ?? d.showPartyName,
    showPartyAddress: config.party?.showAddress ?? d.showPartyAddress,
    showPartyTin: config.party?.showTin ?? d.showPartyTin,
    showTransactionNumber: config.meta?.showTransactionNumber ?? d.showTransactionNumber,
    showDate: config.meta?.showDate ?? d.showDate,
    showCurrency: config.meta?.showCurrency ?? d.showCurrency,
    showExchangeRate: config.meta?.showExchangeRate ?? d.showExchangeRate,
    showReferenceNumber: config.meta?.showReferenceNumber ?? d.showReferenceNumber,
    showPaymentMethod: config.meta?.showPaymentMethod ?? d.showPaymentMethod,
    showPaymentAccount: config.meta?.showPaymentAccount ?? d.showPaymentAccount,
    showEwt: config.summary?.showEwt ?? d.showEwt,
    showTotal: config.summary?.showTotal ?? d.showTotal,
    showAmountInWords: config.summary?.showAmountInWords ?? d.showAmountInWords,
    showSystemGeneratedNotice: config.summary?.showSystemGeneratedNotice ?? d.showSystemGeneratedNotice,
    showComplianceFooter: config.summary?.showComplianceFooter ?? d.showComplianceFooter,
    showPageFooter: config.summary?.showPageFooter ?? d.showPageFooter,
    sectionOrder: Array.isArray(config.layout?.sectionOrder) && config.layout.sectionOrder.length
      ? config.layout.sectionOrder
      : (DEFAULT_SECTION_ORDER[moduleType] || []),
    spacingPreset: config.layout?.spacingPreset || d.spacingPreset,
    alignmentPreset: config.layout?.alignmentPreset || d.alignmentPreset,
  };
}

// Builds ONLY the config sections/fields Phase 3A actually exposes -
// `table`, `layout`, and `showAppliedInvoices` are never included here, so
// the backend's own merge-onto-built-in-default logic fills those in
// unchanged. This is what keeps "no unsupported config keys sent" true by
// construction, not by a client-side filter that could drift from the
// fields actually rendered above.
function buildConfigPayload(form, moduleType) {
  const isOr = moduleType === "or";
  return {
    header: {
      documentTitle: form.documentTitle.trim() || null,
      subtitle: form.subtitle.trim() || null,
      showCompanyName: form.showCompanyName,
      showCompanyAddress: form.showCompanyAddress,
      showTin: form.showTin,
      showCopyBadge: form.showCopyBadge,
    },
    party: {
      sectionLabel: form.partySectionLabel.trim(),
      showName: form.showPartyName,
      showAddress: form.showPartyAddress,
      showTin: form.showPartyTin,
    },
    meta: {
      showTransactionNumber: form.showTransactionNumber,
      showDate: form.showDate,
      showCurrency: form.showCurrency,
      showExchangeRate: form.showExchangeRate,
      showReferenceNumber: form.showReferenceNumber,
      ...(isOr ? { showPaymentMethod: form.showPaymentMethod, showPaymentAccount: form.showPaymentAccount } : {}),
    },
    summary: {
      showEwt: form.showEwt,
      showTotal: form.showTotal,
      ...(isOr ? { showAmountInWords: form.showAmountInWords } : {}),
      showSystemGeneratedNotice: form.showSystemGeneratedNotice,
      showComplianceFooter: form.showComplianceFooter,
      showPageFooter: form.showPageFooter,
    },
    layout: {
      spacingPreset: form.spacingPreset,
      alignmentPreset: form.alignmentPreset,
      // Never send an empty array - the backend validator requires
      // sectionOrder be non-empty when the key is present at all. If the
      // built-in seed genuinely hasn't loaded yet, omit the key entirely
      // so the server's own merge-onto-default fills it in instead of
      // rejecting the save outright.
      ...(form.sectionOrder && form.sectionOrder.length ? { sectionOrder: form.sectionOrder } : {}),
    },
  };
}

function formatDateTime(value) {
  if (!value) return "—";
  try {
    return new Date(value).toLocaleString("en-PH", { dateStyle: "medium", timeStyle: "short" });
  } catch {
    return "—";
  }
}

export default function PrintTemplateList({ moduleType }) {
  const meta = MODULE_META[moduleType];
  const { can, loading: permsLoading } = usePermissions();

  const [templates, setTemplates] = useState([]);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState("");
  const [banner, setBanner] = useState(null);

  const [showFormModal, setShowFormModal] = useState(false);
  const [formMode, setFormMode] = useState("add"); // "add" | "edit" | "view"
  const [editingTemplate, setEditingTemplate] = useState(null);
  const [originalVariant, setOriginalVariant] = useState(null);
  const [form, setForm] = useState(emptyMainForm(moduleType));
  const [configForm, setConfigForm] = useState(emptyConfigForm(moduleType));
  const [formError, setFormError] = useState("");
  const [saving, setSaving] = useState(false);
  const [dirty, setDirty] = useState(false);

  const [confirmAction, setConfirmAction] = useState(null); // { type: "set-default" | "deactivate", template }
  const [confirmBusy, setConfirmBusy] = useState(false);

  // ---- Phase 3B: live preview ----
  const [previewTransactions, setPreviewTransactions] = useState([]);
  const [previewTransactionId, setPreviewTransactionId] = useState("");
  const [previewTransactionsError, setPreviewTransactionsError] = useState("");
  const [builtInConfig, setBuiltInConfig] = useState(null);
  const [previewingBuiltIn, setPreviewingBuiltIn] = useState(false);
  const [previewUrl, setPreviewUrl] = useState(null);
  const [previewLoading, setPreviewLoading] = useState(false);
  const [previewError, setPreviewError] = useState("");
  const previewUrlRef = useRef(null);

  const canView = permsLoading || can(MODULE_KEY, "VIEW");
  const canCreate = can(MODULE_KEY, "CREATE");
  const canEdit = can(MODULE_KEY, "EDIT");
  const canActivate = can(MODULE_KEY, "ACTIVATE");
  const canDeactivate = can(MODULE_KEY, "DEACTIVATE");
  const canSetDefault = can(MODULE_KEY, "SET_DEFAULT");

  useEffect(() => {
    loadTemplates();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [moduleType]);

  useEffect(() => {
    if (!banner) return;
    const t = setTimeout(() => setBanner(null), 5000);
    return () => clearTimeout(t);
  }, [banner]);

  // Revoke the last Blob URL on unmount only - refreshes revoke their own
  // predecessor inline (see runPreviewNow) so there is never more than one
  // live Blob URL outstanding at a time.
  useEffect(() => {
    return () => {
      if (previewUrlRef.current) URL.revokeObjectURL(previewUrlRef.current);
    };
  }, []);

  // Loads the two preview inputs the Builder needs, fresh every time a
  // template is opened: (1) existing transactions this user is actually
  // authorized to print, for the transaction selector, and (2) the
  // module's own built-in default config, for both "Preview built-in
  // default instead" and "Reset to System Default". A 403 on the
  // transaction list (a real, expected state - PRINT.DOCUMENT_TEMPLATES
  // and TRANSACTIONS.INVOICE/OR.VIEW are independent permissions) degrades
  // to the "no transaction available" empty state rather than an error,
  // since editing/saving a template must still work either way.
  async function loadPreviewData(isNewTemplate) {
    setPreviewTransactions([]);
    setPreviewTransactionId("");
    setPreviewTransactionsError("");
    setPreviewingBuiltIn(false);
    setPreviewError("");
    if (previewUrlRef.current) {
      URL.revokeObjectURL(previewUrlRef.current);
      previewUrlRef.current = null;
    }
    setPreviewUrl(null);

    try {
      const [listRes, builtInRes] = await Promise.all([
        fetch(`${API_BASE}${meta.listEndpoint}`, { headers: authHeaders() }),
        fetch(`${API_BASE}/api/print-templates/built-in?moduleType=${moduleType}`, { headers: authHeaders() }),
      ]);
      if (listRes.ok) {
        const listData = await listRes.json();
        const rows = Array.isArray(listData) ? listData : [];
        setPreviewTransactions(rows);
        if (rows.length) setPreviewTransactionId(String(rows[0].id));
      } else if (listRes.status === 403) {
        setPreviewTransactionsError(`You do not have permission to view existing ${meta.title.toLowerCase()} for preview.`);
      } else {
        setPreviewTransactionsError("Unable to load transactions for preview.");
      }
      if (builtInRes.ok) {
        const builtInData = await builtInRes.json();
        setBuiltInConfig(builtInData.config);
        // Phase 3C: a brand-new template's Layout section starts from the
        // REAL built-in order (fetched here, the single source of truth),
        // never a hardcoded frontend duplicate. Guarded so it never
        // clobbers an order the user may have already started customizing
        // in the brief window before this fetch resolves.
        if (isNewTemplate && Array.isArray(builtInData.config?.layout?.sectionOrder)) {
          setConfigForm((prev) => (prev.sectionOrder.length ? prev : { ...prev, sectionOrder: builtInData.config.layout.sectionOrder }));
        }
      }
    } catch (err) {
      console.error("LOAD PREVIEW DATA ERROR:", err);
      setPreviewTransactionsError("Unable to connect to server.");
    }
  }

  // The single preview call, shared by the debounced auto-refresh effect
  // below and the manual "Refresh Preview" button - never triggers a save,
  // never touches configForm/form, and a failure here leaves the last
  // successful previewUrl on screen untouched (only previewError changes),
  // so a transient/validation error never blanks out what the user was
  // already looking at or discards their unsaved edits.
  const runPreviewNow = useCallback(async () => {
    if (!previewTransactionId) return;
    setPreviewLoading(true);
    setPreviewError("");
    try {
      // builtInDefaultConfig() always returns every field the module's
      // built-in layout could ever use (e.g. summary.showAppliedInvoices
      // is present - as false - even for Invoice), which is fine as
      // internal/stored shape but is NOT valid client INPUT: the Phase 2
      // validator rejects showAppliedInvoices/appliedInvoiceColumns
      // outright for a non-OR moduleType, by key presence, not truthiness.
      // Routing it through configToForm -> buildConfigPayload (the exact
      // same normalization every other save/preview already uses) strips
      // those module-inappropriate keys the same way loading an existing
      // saved template's config already does, rather than forwarding the
      // built-in object's raw shape.
      const configToSend = previewingBuiltIn
        ? (builtInConfig ? buildConfigPayload(configToForm(builtInConfig, moduleType), moduleType) : null)
        : buildConfigPayload(configForm, moduleType);
      if (!configToSend) return;
      const res = await fetch(`${API_BASE}/api/print-templates/preview`, {
        method: "POST",
        headers: { "Content-Type": "application/json", ...authHeaders() },
        body: JSON.stringify({ moduleType, transactionId: previewTransactionId, config: configToSend }),
      });
      const data = await res.json();
      if (!res.ok) {
        setPreviewError(data.message || "Failed to generate preview.");
        return;
      }
      const bytes = await buildDocumentPdf({
        ...data,
        transactionType: moduleType,
        mode: "without_entries",
        generatedBy: currentUsername(),
        copyType: "Original",
        copies: 1,
      });
      const blob = new Blob([bytes], { type: "application/pdf" });
      const url = URL.createObjectURL(blob);
      if (previewUrlRef.current) URL.revokeObjectURL(previewUrlRef.current);
      previewUrlRef.current = url;
      setPreviewUrl(url);
    } catch (err) {
      console.error("PREVIEW ERROR:", err);
      setPreviewError("Unable to connect to server while generating preview.");
    } finally {
      setPreviewLoading(false);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [previewTransactionId, configForm, previewingBuiltIn, builtInConfig, moduleType]);

  // Debounced auto-refresh: any change to the working config, the selected
  // preview transaction, or the built-in/working toggle schedules a single
  // refresh 500ms later, coalescing rapid keystrokes into one request
  // instead of one per keystroke.
  useEffect(() => {
    if (!showFormModal || !previewTransactionId) return;
    const timer = setTimeout(() => {
      runPreviewNow();
    }, 500);
    return () => clearTimeout(timer);
  }, [showFormModal, previewTransactionId, configForm, previewingBuiltIn, builtInConfig, runPreviewNow]);

  function handleResetToBuiltIn() {
    if (!builtInConfig) return;
    if (dirty && !window.confirm("Reset to the built-in system default? This will discard your current unsaved configuration changes.")) {
      return;
    }
    setConfigForm(configToForm(builtInConfig, moduleType));
    setDirty(true);
  }

  async function loadTemplates() {
    setLoading(true);
    setLoadError("");
    try {
      const res = await fetch(`${API_BASE}/api/print-templates?moduleType=${moduleType}`, { headers: authHeaders() });
      const data = await res.json();
      if (!res.ok) {
        setLoadError(data.message || "Failed to load templates.");
        return;
      }
      setTemplates(Array.isArray(data) ? data : []);
    } catch (err) {
      console.error("LOAD PRINT TEMPLATES ERROR:", err);
      setLoadError("Unable to connect to server.");
    } finally {
      setLoading(false);
    }
  }

  const sortedTemplates = useMemo(
    () => [...templates].sort((a, b) => (b.isDefault - a.isDefault) || a.templateName.localeCompare(b.templateName)),
    [templates]
  );

  function openAdd() {
    setForm(emptyMainForm(moduleType));
    setConfigForm(emptyConfigForm(moduleType));
    setEditingTemplate(null);
    setOriginalVariant(null);
    setFormMode("add");
    setFormError("");
    setDirty(false);
    setShowFormModal(true);
    loadPreviewData(true);
  }

  function openEditOrView(template) {
    setForm({
      templateName: template.templateName,
      templateCode: template.templateCode,
      documentVariant: template.documentVariant,
    });
    setConfigForm(configToForm(template.config, moduleType));
    setEditingTemplate(template);
    setOriginalVariant(template.documentVariant);
    setFormMode(canEdit ? "edit" : "view");
    setFormError("");
    setDirty(false);
    setShowFormModal(true);
    loadPreviewData();
  }

  function requestCloseModal() {
    if (dirty && !window.confirm("Discard unsaved changes to this template?")) return;
    setShowFormModal(false);
  }

  function updateForm(key, value) {
    setForm((prev) => ({ ...prev, [key]: value }));
    setDirty(true);
  }

  function updateConfig(key, value) {
    setConfigForm((prev) => ({ ...prev, [key]: value }));
    setDirty(true);
  }

  function validateForm() {
    if (!form.templateName.trim()) return "Template Name is required.";
    if (form.templateName.length > 150) return "Template Name must be at most 150 characters.";
    if (formMode === "add") {
      if (!form.templateCode.trim()) return "Template Code is required.";
      if (!TEMPLATE_CODE_PATTERN.test(form.templateCode.trim())) {
        return "Template Code must be 3-60 characters, lowercase letters/digits/underscore/hyphen only, and cannot start or end with a separator.";
      }
    }
    if (!meta.variants.some((v) => v.value === form.documentVariant)) return "Select a valid document variant.";
    if (!configForm.partySectionLabel.trim()) return "Party Section Label is required.";
    if (!configForm.sectionOrder || configForm.sectionOrder.length === 0) {
      return "Please wait for the template configuration to finish loading before saving.";
    }
    return null;
  }

  // Phase 3C: swaps two adjacent entries in the working sectionOrder array.
  // No drag-and-drop, no arbitrary positions - a section can only ever
  // trade places with its immediate neighbor, one step at a time.
  function moveSection(index, direction) {
    const target = index + direction;
    if (target < 0 || target >= configForm.sectionOrder.length) return;
    const next = [...configForm.sectionOrder];
    [next[index], next[target]] = [next[target], next[index]];
    updateConfig("sectionOrder", next);
  }

  async function handleSave() {
    const validationError = validateForm();
    if (validationError) {
      setFormError(validationError);
      return;
    }
    setSaving(true);
    setFormError("");
    try {
      const config = buildConfigPayload(configForm, moduleType);
      let res;
      if (formMode === "add") {
        res = await fetch(`${API_BASE}/api/print-templates`, {
          method: "POST",
          headers: { "Content-Type": "application/json", ...authHeaders() },
          body: JSON.stringify({
            moduleType,
            templateCode: form.templateCode.trim(),
            templateName: form.templateName.trim(),
            documentVariant: form.documentVariant,
            config,
          }),
        });
      } else {
        res = await fetch(`${API_BASE}/api/print-templates/${editingTemplate.id}`, {
          method: "PUT",
          headers: { "Content-Type": "application/json", ...authHeaders() },
          body: JSON.stringify({
            templateName: form.templateName.trim(),
            documentVariant: form.documentVariant,
            config,
          }),
        });
      }
      const data = await res.json();
      if (!res.ok) {
        setFormError(data.message || "Failed to save template.");
        return;
      }
      setShowFormModal(false);
      setBanner({ type: "success", message: `"${data.templateName}" ${formMode === "add" ? "created" : "updated"} successfully.` });
      await loadTemplates();
    } catch (err) {
      console.error("SAVE PRINT TEMPLATE ERROR:", err);
      setFormError("Unable to connect to server.");
    } finally {
      setSaving(false);
    }
  }

  function requestSetDefault(template) {
    setConfirmAction({ type: "set-default", template });
  }

  function requestDeactivate(template) {
    setConfirmAction({ type: "deactivate", template });
  }

  async function handleActivate(template) {
    setConfirmBusy(true);
    try {
      const res = await fetch(`${API_BASE}/api/print-templates/${template.id}/activate`, { method: "POST", headers: authHeaders() });
      const data = await res.json();
      if (!res.ok) {
        setBanner({ type: "error", message: data.message || "Failed to activate template." });
        return;
      }
      setBanner({ type: "success", message: `"${template.templateName}" activated.` });
      await loadTemplates();
    } catch (err) {
      console.error("ACTIVATE PRINT TEMPLATE ERROR:", err);
      setBanner({ type: "error", message: "Unable to connect to server." });
    } finally {
      setConfirmBusy(false);
    }
  }

  async function performConfirmAction() {
    if (!confirmAction) return;
    const { type, template } = confirmAction;
    setConfirmBusy(true);
    try {
      const path = type === "set-default" ? "set-default" : "deactivate";
      const res = await fetch(`${API_BASE}/api/print-templates/${template.id}/${path}`, { method: "POST", headers: authHeaders() });
      const data = await res.json();
      if (!res.ok) {
        setBanner({ type: "error", message: data.message || `Failed to ${type === "set-default" ? "set default" : "deactivate"} template.` });
        return;
      }
      setBanner({
        type: "success",
        message: type === "set-default"
          ? `"${template.templateName}" is now the default ${meta.singularNoun} template.`
          : `"${template.templateName}" deactivated.`,
      });
      await loadTemplates();
    } catch (err) {
      console.error("PRINT TEMPLATE ACTION ERROR:", err);
      setBanner({ type: "error", message: "Unable to connect to server." });
    } finally {
      setConfirmBusy(false);
      setConfirmAction(null);
    }
  }

  if (!canView) {
    return (
      <div className="fs-page">
        <div className="fs-card">You do not have permission to view {meta.title}.</div>
      </div>
    );
  }

  const existingDefault = editingTemplate
    ? templates.find((t) => t.isDefault && t.id !== editingTemplate.id)
    : templates.find((t) => t.isDefault);

  const variantChanged = formMode === "edit" && originalVariant && form.documentVariant !== originalVariant;
  const readOnly = formMode === "view";

  return (
    <div className="fs-page">
      <div className="fs-header">
        <div>
          <h1>{meta.title}</h1>
          <p>{meta.subtitle}</p>
        </div>
        {canCreate && (
          <button className="fs-btn primary" onClick={openAdd}>
            + New Template
          </button>
        )}
      </div>

      {banner && <div className={`ptl-banner ptl-banner-${banner.type}`}>{banner.message}</div>}

      <div className="fs-card">
        <table className="fs-table">
          <thead>
            <tr>
              <th>Template Name</th>
              <th>Module</th>
              <th>Variant</th>
              <th>Default</th>
              <th>Active</th>
              <th>Updated At</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr>
                <td colSpan="7" className="fs-empty">Loading templates…</td>
              </tr>
            ) : loadError ? (
              <tr>
                <td colSpan="7" className="fs-empty ptl-error-text">{loadError}</td>
              </tr>
            ) : sortedTemplates.length === 0 ? (
              <tr>
                <td colSpan="7" className="fs-empty">
                  No custom templates yet. Every {meta.singularNoun} prints using the built-in default layout
                  until you create one.
                  {canCreate ? ' Click "+ New Template" to get started.' : ""}
                </td>
              </tr>
            ) : (
              sortedTemplates.map((t) => (
                <tr key={t.id}>
                  <td>{t.templateName}</td>
                  <td>{moduleType === "or" ? "OR" : "Invoice"}</td>
                  <td>{meta.variants.find((v) => v.value === t.documentVariant)?.label || t.documentVariant}</td>
                  <td>{t.isDefault ? <span className="ptl-badge ptl-badge-default">DEFAULT</span> : "—"}</td>
                  <td>
                    <span className={`ptl-badge ${t.isActive ? "ptl-badge-active" : "ptl-badge-inactive"}`}>
                      {t.isActive ? "Active" : "Inactive"}
                    </span>
                  </td>
                  <td>{formatDateTime(t.updatedAt)}</td>
                  <td className="ptl-actions-cell">
                    <button className="fs-btn ptl-btn-sm" onClick={() => openEditOrView(t)}>
                      {canEdit ? "Edit" : "View"}
                    </button>
                    {t.isActive && canSetDefault && !t.isDefault && (
                      <button className="fs-btn ptl-btn-sm" onClick={() => requestSetDefault(t)}>Set Default</button>
                    )}
                    {t.isActive && canDeactivate && (
                      <button className="fs-btn ptl-btn-sm" onClick={() => requestDeactivate(t)}>Deactivate</button>
                    )}
                    {!t.isActive && canActivate && (
                      <button className="fs-btn ptl-btn-sm" onClick={() => handleActivate(t)} disabled={confirmBusy}>Activate</button>
                    )}
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {showFormModal && (
        <div className="ptl-overlay" role="dialog" aria-modal="true">
          <div className="ptl-modal ptl-modal-wide">
            <div className="ptl-modal-header">
              <h2>
                {formMode === "add" ? `New ${meta.title.replace(" Templates", "")} Template`
                  : formMode === "view" ? `View "${form.templateName}"`
                  : `Edit "${form.templateName}"`}
              </h2>
              <button className="ptl-close" onClick={requestCloseModal} aria-label="Close">&times;</button>
            </div>

            <div className="ptl-modal-body ptl-builder-body">
              {formError && <div className="ptl-banner ptl-banner-error">{formError}</div>}
              {readOnly && (
                <div className="ptl-banner ptl-banner-info">
                  You have view-only access to print templates. Editing requires the EDIT permission.
                </div>
              )}

            <div className="ptl-builder-columns">
            <div className="ptl-builder-config-col">
              <div className="fs-grid ptl-main-fields">
                <div className="fs-field">
                  <label>Template Name</label>
                  <input
                    value={form.templateName}
                    onChange={(e) => updateForm("templateName", e.target.value)}
                    placeholder="e.g. Standard Sales Invoice"
                    disabled={readOnly}
                  />
                </div>
                <div className="fs-field">
                  <label title="Cannot be changed after creation.">Template Code {formMode !== "add" && "(fixed)"}</label>
                  <input
                    value={form.templateCode}
                    onChange={(e) => updateForm("templateCode", e.target.value.toLowerCase())}
                    placeholder="e.g. standard-sales-invoice"
                    disabled={formMode !== "add"}
                  />
                </div>
                <div className="fs-field">
                  <label>Document Variant</label>
                  <select
                    value={form.documentVariant}
                    onChange={(e) => updateForm("documentVariant", e.target.value)}
                    disabled={readOnly}
                  >
                    {meta.variants.map((v) => (
                      <option key={v.value} value={v.value}>{v.label}</option>
                    ))}
                  </select>
                </div>
              </div>

              {variantChanged && (
                <div className="ptl-banner ptl-banner-info ptl-variant-warning">
                  Changing the document variant does not automatically change the layout configuration.
                </div>
              )}

              {existingDefault && formMode !== "view" && (
                <p className="ptl-hint">
                  Current default {meta.singularNoun} template: <strong>{existingDefault.templateName}</strong>.
                  Use "Set Default" from the template list to change it.
                </p>
              )}

              {!readOnly && (
                <button
                  type="button"
                  className="ptl-btn-secondary ptl-btn-sm ptl-reset-builtin-btn"
                  onClick={handleResetToBuiltIn}
                  disabled={!builtInConfig}
                  title="Replaces your in-progress configuration below with the built-in system default. Does not save, and does not change your current default template."
                >
                  Reset to System Default
                </button>
              )}

              <ConfigSection title="Header">
                <div className="fs-field">
                  <label>Document Title</label>
                  <input
                    value={configForm.documentTitle}
                    onChange={(e) => updateConfig("documentTitle", e.target.value)}
                    placeholder={moduleType === "or" ? "OFFICIAL RECEIPT" : "INVOICE"}
                    disabled={readOnly}
                  />
                </div>
                <div className="fs-field">
                  <label>Subtitle</label>
                  <input
                    value={configForm.subtitle}
                    onChange={(e) => updateConfig("subtitle", e.target.value)}
                    placeholder="Optional"
                    disabled={readOnly}
                  />
                </div>
                <Toggle label="Show Company Name" checked={configForm.showCompanyName} onChange={(v) => updateConfig("showCompanyName", v)} disabled={readOnly} />
                <Toggle label="Show Company Address" checked={configForm.showCompanyAddress} onChange={(v) => updateConfig("showCompanyAddress", v)} disabled={readOnly} />
                <Toggle label="Show TIN" checked={configForm.showTin} onChange={(v) => updateConfig("showTin", v)} disabled={readOnly} />
                <Toggle label="Show Copy Badge" checked={configForm.showCopyBadge} onChange={(v) => updateConfig("showCopyBadge", v)} disabled={readOnly} />
              </ConfigSection>

              <ConfigSection title={moduleType === "or" ? "Received From" : "Party"}>
                <div className="fs-field">
                  <label>Section Label</label>
                  <input
                    value={configForm.partySectionLabel}
                    onChange={(e) => updateConfig("partySectionLabel", e.target.value)}
                    placeholder={meta.defaultPartyLabel}
                    disabled={readOnly}
                  />
                </div>
                <Toggle label="Show Name" checked={configForm.showPartyName} onChange={(v) => updateConfig("showPartyName", v)} disabled={readOnly} />
                <Toggle label="Show Address" checked={configForm.showPartyAddress} onChange={(v) => updateConfig("showPartyAddress", v)} disabled={readOnly} />
                <Toggle label="Show TIN" checked={configForm.showPartyTin} onChange={(v) => updateConfig("showPartyTin", v)} disabled={readOnly} />
              </ConfigSection>

              <ConfigSection title={moduleType === "or" ? "Payment Metadata" : "Transaction Details"}>
                <Toggle label="Show Transaction Number" checked={configForm.showTransactionNumber} onChange={(v) => updateConfig("showTransactionNumber", v)} disabled={readOnly} />
                <Toggle label="Show Date" checked={configForm.showDate} onChange={(v) => updateConfig("showDate", v)} disabled={readOnly} />
                <Toggle label="Show Currency" checked={configForm.showCurrency} onChange={(v) => updateConfig("showCurrency", v)} disabled={readOnly} />
                <Toggle label="Show Exchange Rate" checked={configForm.showExchangeRate} onChange={(v) => updateConfig("showExchangeRate", v)} disabled={readOnly} />
                <Toggle label="Show Reference Number" checked={configForm.showReferenceNumber} onChange={(v) => updateConfig("showReferenceNumber", v)} disabled={readOnly} />
                {moduleType === "or" && (
                  <>
                    <Toggle label="Show Payment Method" checked={configForm.showPaymentMethod} onChange={(v) => updateConfig("showPaymentMethod", v)} disabled={readOnly} />
                    <Toggle label="Show Payment Account" checked={configForm.showPaymentAccount} onChange={(v) => updateConfig("showPaymentAccount", v)} disabled={readOnly} />
                  </>
                )}
              </ConfigSection>

              <ConfigSection title="Summary">
                <Toggle label="Show EWT" checked={configForm.showEwt} onChange={(v) => updateConfig("showEwt", v)} disabled={readOnly} />
                <Toggle label="Show Total" checked={configForm.showTotal} onChange={(v) => updateConfig("showTotal", v)} disabled={readOnly} />
                {moduleType === "or" && (
                  <Toggle label="Show Amount in Words" checked={configForm.showAmountInWords} onChange={(v) => updateConfig("showAmountInWords", v)} disabled={readOnly} />
                )}
              </ConfigSection>

              <ConfigSection title="Footer">
                <Toggle label="Show System-Generated Notice" checked={configForm.showSystemGeneratedNotice} onChange={(v) => updateConfig("showSystemGeneratedNotice", v)} disabled={readOnly} />
                <Toggle label="Show Compliance Footer" checked={configForm.showComplianceFooter} onChange={(v) => updateConfig("showComplianceFooter", v)} disabled={readOnly} />
                <Toggle label="Show Page Footer" checked={configForm.showPageFooter} onChange={(v) => updateConfig("showPageFooter", v)} disabled={readOnly} />
              </ConfigSection>

              <ConfigSection title="Layout">
                <div className="fs-field">
                  <label>Spacing</label>
                  <select
                    value={configForm.spacingPreset}
                    onChange={(e) => updateConfig("spacingPreset", e.target.value)}
                    disabled={readOnly}
                  >
                    {SPACING_PRESETS.map((p) => (
                      <option key={p.value} value={p.value}>{p.label}</option>
                    ))}
                  </select>
                </div>
                <div className="fs-field">
                  <label>Header Alignment</label>
                  <select
                    value={configForm.alignmentPreset}
                    onChange={(e) => updateConfig("alignmentPreset", e.target.value)}
                    disabled={readOnly}
                  >
                    {ALIGNMENT_PRESETS.map((p) => (
                      <option key={p.value} value={p.value}>{p.label}</option>
                    ))}
                  </select>
                </div>

                <div className="ptl-section-order-wrap">
                  <label className="ptl-section-order-label">Section Order</label>
                  {configForm.sectionOrder.length === 0 ? (
                    <p className="ptl-hint">Loading section order…</p>
                  ) : (
                    <ol className="ptl-section-order-list">
                      {configForm.sectionOrder.map((key, idx) => (
                        <li key={key} className="ptl-section-order-row">
                          <span className="ptl-section-order-name">{SECTION_LABELS[key] || key}</span>
                          <div className="ptl-section-order-actions">
                            <button
                              type="button"
                              className="ptl-btn-secondary ptl-btn-sm"
                              onClick={() => moveSection(idx, -1)}
                              disabled={readOnly || idx === 0}
                              aria-label={`Move ${SECTION_LABELS[key] || key} up`}
                            >
                              ↑
                            </button>
                            <button
                              type="button"
                              className="ptl-btn-secondary ptl-btn-sm"
                              onClick={() => moveSection(idx, 1)}
                              disabled={readOnly || idx === configForm.sectionOrder.length - 1}
                              aria-label={`Move ${SECTION_LABELS[key] || key} down`}
                            >
                              ↓
                            </button>
                          </div>
                        </li>
                      ))}
                      <li className="ptl-section-order-row ptl-section-order-fixed">
                        <span className="ptl-section-order-name">Footer (signatures &amp; compliance notice — always last)</span>
                      </li>
                    </ol>
                  )}
                  <p className="ptl-future-hint">
                    Sections can only be moved up or down one step at a time. Visibility is controlled by each
                    section's own Show/Hide settings above, not by this list.
                  </p>
                </div>
              </ConfigSection>

              <ConfigSection title="Not Yet Available" muted>
                <p className="ptl-future-hint">
                  Logo, status badge, payment terms, itemized quantity/unit price/discount, VAT-rate breakdown, and
                  BIR compliance fields (ATP/PTU/Permit/Approved Serial Nos.) are not supported by this system yet -
                  they are not shown as editable controls to avoid saving values that would never actually print.
                </p>
              </ConfigSection>
            </div>

            <div className="ptl-builder-preview-col">
              <div className="ptl-preview-toolbar">
                <select
                  className="ptl-preview-tx-select"
                  value={previewTransactionId}
                  onChange={(e) => setPreviewTransactionId(e.target.value)}
                  disabled={previewTransactions.length === 0}
                >
                  {previewTransactions.length === 0 ? (
                    <option value="">No transactions available</option>
                  ) : (
                    previewTransactions.map((t) => (
                      <option key={t.id} value={t.id}>
                        {t.voucherNo} — {t.customerName || "—"} ({t.transactionDate})
                      </option>
                    ))
                  )}
                </select>
                <button
                  type="button"
                  className="ptl-btn-secondary ptl-btn-sm"
                  onClick={() => runPreviewNow()}
                  disabled={!previewTransactionId || previewLoading}
                >
                  {previewLoading ? "Refreshing…" : "Refresh Preview"}
                </button>
                <label className="ptl-toggle ptl-preview-builtin-toggle">
                  <input
                    type="checkbox"
                    checked={previewingBuiltIn}
                    onChange={(e) => setPreviewingBuiltIn(e.target.checked)}
                    disabled={!builtInConfig || !previewTransactionId}
                  />
                  <span>Preview built-in default instead</span>
                </label>
              </div>

              {previewTransactionsError && <div className="ptl-banner ptl-banner-info">{previewTransactionsError}</div>}
              {previewError && <div className="ptl-banner ptl-banner-error">{previewError}</div>}

              <div className="ptl-preview-frame-wrap">
                {previewTransactions.length === 0 ? (
                  <div className="ptl-preview-placeholder">
                    No transaction available for preview.
                    {previewTransactionsError ? "" : ` You can still edit and save this template - preview will become
                    available once an existing ${meta.singularNoun} exists in this company.`}
                  </div>
                ) : previewUrl ? (
                  <iframe title="Template preview" src={previewUrl} className="ptl-preview-frame" />
                ) : (
                  <div className="ptl-preview-placeholder">
                    {previewLoading ? "Generating preview…" : "Select a transaction above to preview this template."}
                  </div>
                )}
              </div>
            </div>
            </div>
            </div>

            <div className="ptl-modal-footer">
              <button className="ptl-btn-secondary" onClick={requestCloseModal} disabled={saving}>
                {readOnly ? "Close" : "Cancel"}
              </button>
              {!readOnly && (
                <button className="ptl-btn-primary" onClick={handleSave} disabled={saving}>
                  {saving ? "Saving…" : formMode === "add" ? "Save Template" : "Update Template"}
                </button>
              )}
            </div>
          </div>
        </div>
      )}

      {confirmAction && (
        <div className="ptl-overlay" role="dialog" aria-modal="true">
          <div className="ptl-modal ptl-modal-narrow">
            <div className="ptl-modal-header">
              <h2>{confirmAction.type === "set-default" ? "Set Default Template" : "Deactivate Template"}</h2>
              <button className="ptl-close" onClick={() => setConfirmAction(null)} aria-label="Close">&times;</button>
            </div>
            <div className="ptl-modal-body">
              {confirmAction.type === "set-default" ? (
                <p>
                  Set <strong>{confirmAction.template.templateName}</strong> as the default {meta.singularNoun} template?
                  {existingDefault && existingDefault.id !== confirmAction.template.id && (
                    <> This will replace <strong>{existingDefault.templateName}</strong> as the current default.</>
                  )}
                </p>
              ) : (
                <p>
                  Deactivate <strong>{confirmAction.template.templateName}</strong>?
                  {confirmAction.template.isDefault && (
                    <> This template is currently the default - deactivating it will clear its default status, and
                    printing will fall back to the built-in layout until you set a new default.</>
                  )}
                </p>
              )}
            </div>
            <div className="ptl-modal-footer">
              <button className="ptl-btn-secondary" onClick={() => setConfirmAction(null)} disabled={confirmBusy}>Cancel</button>
              <button className="ptl-btn-primary" onClick={performConfirmAction} disabled={confirmBusy}>
                {confirmBusy ? "Working…" : "Confirm"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function ConfigSection({ title, children, muted }) {
  return (
    <div className={`ptl-section${muted ? " ptl-section-muted" : ""}`}>
      <h3 className="ptl-section-title">{title}</h3>
      <div className="ptl-section-body">{children}</div>
    </div>
  );
}

function Toggle({ label, checked, onChange, disabled }) {
  return (
    <label className="ptl-toggle">
      <input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} disabled={disabled} />
      <span>{label}</span>
    </label>
  );
}
