import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

// Shared low-level PDF drawing primitives so invoicePdfBuilder.js and
// invoiceListPdfBuilder.js (and future Phase 2/3 module builders) don't
// each reimplement page management / text drawing - mirrors the pattern
// already proven in Quotation.jsx's downloadPDF(), factored out so it's
// reusable instead of copy-pasted per module.

export const A4 = { width: 595.28, height: 841.89 };

// Deterministic box height for drawCopyBadge (9pt text + 5pt padding top
// and bottom) - exported so callers can reserve clearance for it without
// a magic number, instead of guessing how tall the badge box is.
export const COPY_BADGE_HEIGHT = 19;

export const COLORS = {
  dark: rgb(0.06, 0.09, 0.16),
  grey: rgb(0.42, 0.45, 0.5),
  lightGrey: rgb(0.95, 0.95, 0.96),
  border: rgb(0.85, 0.85, 0.87),
  accent: rgb(0.09, 0.13, 0.24),
  danger: rgb(0.72, 0.11, 0.11),
  white: rgb(1, 1, 1),
};

export async function createPdfKit({ pageSize = A4, marginX = 40, marginTop = 40, marginBottom = 50 } = {}) {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const italicFont = await pdfDoc.embedFont(StandardFonts.HelveticaOblique);

  const pages = [];
  let page;
  let y;

  function addPage() {
    page = pdfDoc.addPage([pageSize.width, pageSize.height]);
    y = pageSize.height - marginTop;
    pages.push(page);
  }
  addPage();

  const kit = {
    pdfDoc,
    font,
    boldFont,
    italicFont,
    marginX,
    pageWidth: pageSize.width,
    pageHeight: pageSize.height,
    getY: () => y,
    setY: (v) => {
      y = v;
    },
    moveDown: (amount) => {
      y -= amount;
    },
    // Returns true when it had to start a new page, so callers that draw a
    // repeating table header know to redraw it.
    ensureRoom: (needed) => {
      if (y - needed < marginBottom) {
        addPage();
        return true;
      }
      return false;
    },
    // Unconditional new page - used between document copies (Original/
    // Duplicate/Customer Copy/...) so each copy starts fresh regardless of
    // how much room was left on the previous copy's last page.
    forcePageBreak: () => {
      addPage();
    },
    // Small bordered badge in the top-right of the CURRENT page, used to
    // stamp which copy (Original/Duplicate/Customer Copy/...) a document
    // is. `topY` anchors the TOP of the badge box - callers that also
    // draw a title/voucher-number block in the top-right corner must pass
    // the SAME anchor those use (see COPY_BADGE_HEIGHT below) so the two
    // never land in the same vertical band. Defaults to a page-relative
    // position for callers that don't need to coordinate it with anything
    // else in the top-right corner.
    drawCopyBadge: (text, { topY = pageSize.height - 24 } = {}) => {
      if (!text) return;
      const size = 9;
      const padX = 10;
      const padY = 5;
      const label = String(text).toUpperCase();
      const w = boldFont.widthOfTextAtSize(label, size) + padX * 2;
      const h = size + padY * 2;
      const x = pageSize.width - marginX - w;
      page.drawRectangle({
        x,
        y: topY - h,
        width: w,
        height: h,
        borderColor: COLORS.dark,
        borderWidth: 1,
        color: COLORS.lightGrey,
      });
      page.drawText(label, { x: x + padX, y: topY - h + padY, size, font: boldFont, color: COLORS.dark });
    },
    drawText: (text, x, opts = {}) => {
      page.drawText(String(text ?? ""), {
        x,
        y: opts.y ?? y,
        size: opts.size || 9.5,
        font: opts.bold ? boldFont : opts.italic ? italicFont : font,
        color: opts.color || COLORS.dark,
      });
    },
    drawRight: (text, xRight, opts = {}) => {
      const size = opts.size || 9.5;
      const useFont = opts.bold ? boldFont : opts.italic ? italicFont : font;
      const str = String(text ?? "");
      const w = useFont.widthOfTextAtSize(str, size);
      kit.drawText(str, xRight - w, opts);
    },
    drawLine: ({ x1, x2, yPos, thickness = 0.75, color = COLORS.border }) => {
      page.drawLine({ start: { x: x1, y: yPos ?? y }, end: { x: x2, y: yPos ?? y }, thickness, color });
    },
    drawRect: ({ x, w, h, color, yPos }) => {
      page.drawRectangle({ x, y: yPos ?? y, width: w, height: h, color });
    },
    async finish({ generatedBy, generatedAt, watermark } = {}) {
      const total = pages.length;
      pages.forEach((p, idx) => {
        const footer = `Page ${idx + 1} of ${total}   ·   Generated by ${generatedBy || "-"} on ${generatedAt || ""}`;
        p.drawText(footer, { x: marginX, y: 24, size: 7.5, font, color: COLORS.grey });

        if (watermark) {
          p.drawText(watermark, {
            x: pageSize.width / 2 - 110,
            y: pageSize.height / 2,
            size: 60,
            font: boldFont,
            color: rgb(0.85, 0.1, 0.1),
            opacity: 0.12,
            rotate: { type: "degrees", angle: 35 },
          });
        }
      });
      return pdfDoc.save();
    },
  };

  return kit;
}

// Simple word-wrap for long particulars/description cells - returns an
// array of lines that each fit within maxWidth at the given font/size.
export function wrapText(text, font, size, maxWidth) {
  const words = String(text ?? "").split(/\s+/).filter(Boolean);
  const lines = [];
  let current = "";

  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, size) > maxWidth && current) {
      lines.push(current);
      current = word;
    } else {
      current = candidate;
    }
  }
  if (current) lines.push(current);
  return lines.length ? lines : [""];
}

export function formatMoney(amount) {
  return Number(amount || 0).toLocaleString("en-PH", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}
